package Java_TodoList.src.com.todo.model;

public class Todo {
    private int id;
    private String title;
    private String description;
    private String status;

    // Constructor method - when we already know the ID (like when reading from the database).
    public Todo(int id, String title, String description, String status){
        this.id = id;
        this.title = title;
        this.description = description;
        this.status = status;
    }

    // Constructor method - when we creating a new todo (ID will be auto-generated by the database).
    public Todo(String title, String description, String status){
        this.title = title;
        this.description = description;
        this.status = status;
    }

    // Getters method
    public int getId(){ return id; }
    public String getTitle(){return title; }
    public String getDescription(){ return description; }
    public String getStatus() { return status; }

    // Setters method
    public void setId(int id){this.id = id;};
    public void setTitle(String title){this.title = title; }
    public void setDescription(String description){ this.description = description; }
    public void setStatus(String status) {this.status = status; }

    // This is called automatically when printing the object (e.g., in a list).
    @Override
    public String toString(){
        return id + ". " + title + " - " + description;
    }
}
